# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_auto_20160615_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesmain',
            name='service_href',
            field=models.CharField(default='', max_length=200),
        ),
    ]
