# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_servicesmain_service_href'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesmain',
            name='service_column_rl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicesmain',
            name='service_is_deploy',
            field=models.BooleanField(default=False),
        ),
    ]
