# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_serviceitems_service_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitems',
            name='service_cost',
            field=models.FloatField(default=0),
        ),
    ]
