# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_auto_20160619_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesmain',
            name='service_column_rl',
        ),
        migrations.AddField(
            model_name='servicesmain',
            name='service_display_serial_item',
            field=models.IntegerField(default=0),
        ),
    ]
