# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_auto_20160619_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('mail_contact', models.EmailField(max_length=254)),
            ],
        ),
    ]
