# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-24 07:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='name_from_contact',
            field=models.CharField(default=datetime.datetime(2016, 6, 24, 7, 12, 53, 549537, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
