# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-15 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_contacts_name_from_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mail_contakt', models.EmailField(max_length=254)),
                ('total_cost_service', models.IntegerField()),
                ('service_in_cart', models.ManyToManyField(to='main_page.ServiceItems')),
            ],
        ),
    ]
