# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-15 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0010_servicecart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecart',
            name='total_cost_service',
            field=models.FloatField(default=0),
        ),
    ]
